export type DocsNavGroup = {
  label: string;
  items: string[];
};

export const docsItemHrefs: Record<string, string> = {
  Introduction: "/docs/introduction",
  Theming: "/docs/theming",
  Changelog: "/docs/changelog",
  License: "/docs/license",
  Color: "/docs/foundations/color",
  Typography: "/docs/foundations/typography",
  Spacing: "/docs/foundations/spacing",
  "Border-radius": "/docs/foundations/border-radius",
  Effects: "/docs/foundations/effects",
  Alert: "/docs/components/alert",
  "Alert Dialog": "/docs/components/alert-dialog",
  "Aspect Ratio": "/docs/components/aspect-ratio",
  Avatar: "/docs/components/avatar",
  Badge: "/docs/components/badge",
  Breadcrumb: "/docs/components/breadcrumb",
  Button: "/docs/components/button",
  Checkbox: "/docs/components/checkbox",
  Dialog: "/docs/components/dialog",
  Divider: "/docs/components/divider",
  Dropdown: "/docs/components/dropdown",
  Input: "/docs/components/input",
  Kbd: "/docs/components/kbd",
  Label: "/docs/components/label",
  Notification: "/docs/components/notification",
  Pagination: "/docs/components/pagination",
  Progress: "/docs/components/progress",
  "Radio Button": "/docs/components/radio-button",
  Select: "/docs/components/select",
  Slider: "/docs/components/slider",
  Switch: "/docs/components/switch",
  Table: "/docs/components/table",
  Tabs: "/docs/components/tabs",
  Textarea: "/docs/components/textarea",
  Toggle: "/docs/components/toggle",
  "Toggle Group": "/docs/components/toggle-group",
  Tooltip: "/docs/components/tooltip",
};

export const docsNavGroups: DocsNavGroup[] = [
  { label: "Getting Started", items: ["Introduction", "Theming", "Changelog", "License"] },
  {
    label: "Foundations",
    items: ["Color", "Typography", "Spacing", "Border-radius", "Effects"],
  },
  {
    label: "Components",
    items: [
      "Alert",
      "Alert Dialog",
      "Aspect Ratio",
      "Avatar",
      "Badge",
      "Breadcrumb",
      "Button",
      "Checkbox",
      "Dialog",
      "Divider",
      "Dropdown",
      "Input",
      "Kbd",
      "Label",
      "Notification",
      "Pagination",
      "Progress",
      "Radio Button",
      "Select",
      "Slider",
      "Switch",
      "Table",
      "Tabs",
      "Textarea",
      "Toggle",
      "Toggle Group",
      "Tooltip",
    ],
  },
];
